Feature/14 item
INU-SPOT/goode-travel-server pull request #21
Opened 2024-09-18 04:47 UTC by X1n9fU

## 📝 관련 이슈 (Related Issues)
> 관련된 이슈 번호를 링크해주세요. 예: close #123 

close #14

## 📌 개요 (Overview)
> 이 Pull Request가 무엇을 하는지 간단히 설명해주세요. 

Item(굳이/계획)에 대한 CRUD 구성

## 💬 검토 포인트 (Review Points)
> 리뷰어가 중점적으로 봐야 할 부분을 작성해주세요.(선택)
> ex) 특정 로직이나 복잡한 부분에 대한 설명, 코드 스타일이나 패턴에 대한 의견

## 📸 스크린샷 (Screenshots)
> 리뷰어의 이해를 도울 수 있는 스크린샷을 첨부해주세요.(선택)

## 💬 추가 설명 (Further Comments)
> 추가적인 논의나 PR 리뷰어가 알아야 할 사항이 있으면 여기에 작성해주세요.(선택)

굳이 관광코스 조회 로직은 관광코스를 구성한 후에 제작 예정입니다.
굳이 상세정보 조회에서 날씨는 날씨 로직 구성 후에 추가할 예정입니다.
공식적인 굳이/계획에 대한 접근에 대하여 따로 예외처리를 구성하였습니다. (ItemAccessException)

2024-09-18 22:42 UTC, squidjiny requested changes
일단 요렇게

2024-09-18 22:42 UTC, squidjiny commented on good2travel/src/main/java/com/spot/good2travel/controller/ItemController.java
> +        if (itemType == ItemType.GOODE){
분기 로직은 서비스 상에서 구현 해 주세요

2024-09-18 22:42 UTC, squidjiny commented on good2travel/src/main/java/com/spot/good2travel/controller/ItemController.java
> +    @PostMapping("/v1/goode")
예전에는 모든걸 goode라고 통칭했지만, item으로 명칭 변경 되면서 좀 더 맞는 url를 생각해야 할 것 같습니다.

2024-09-18 22:42 UTC, squidjiny commented on good2travel/src/main/java/com/spot/good2travel/controller/ItemController.java
> +    @PostMapping("/v1/goodes")
22...

2024-09-18 22:42 UTC, squidjiny commented on good2travel/src/main/java/com/spot/good2travel/controller/ItemController.java
> +    @PutMapping("/v1/goodes/{itemId}")
33...

2024-09-18 22:42 UTC, squidjiny commented on good2travel/src/main/java/com/spot/good2travel/controller/ItemController.java
> +    @PostMapping(value = "/v1/goodes/move", params = "itemId")
44...

2024-09-18 22:42 UTC, squidjiny commented on good2travel/src/main/java/com/spot/good2travel/controller/ItemController.java
> +    @GetMapping("/v1/goodes/{itemId}")
55...

2024-09-18 22:42 UTC, squidjiny commented on good2travel/src/main/java/com/spot/good2travel/controller/ItemController.java
> +                    "<br> 계획의 경우 -> type=PLAN, title, address 필요" +
저희 공식계획에는 localId 필요합니다

2024-09-18 22:42 UTC, squidjiny commented on good2travel/src/main/java/com/spot/good2travel/dto/ItemResponse.java
> +//        private Integer temperature; todo 날씨 로직 추가 이후
날씨 api 뻑나는경우가 많아서
따로 조회 api 만들거같습니다

2024-09-18 23:25 UTC, squidjiny reviewed
추가사항

2024-09-18 23:25 UTC, squidjiny commented on good2travel/src/main/java/com/spot/good2travel/domain/Item.java
제가 이부분 까먹고있다가 검토하면서 생각났는데,

원래는 공식 비공식 할거없이 폴더나 게시글에 추가하면 새로 생성하는거였어서 이모지를 item 폴더에 저장했지만 저번 회의에서 기획이 변경(공식적인 item은 복사하지 말자 -> 후에 item id 기반 다양한 서비스 제공이 가능해짐(여러개가 연결되어 있으니... ex. 이 굳이를 담은 인간수) 되어서 

이제 emoji를 item-foler 테이블에 저장하여야 합니다.
사용자가 각기 다르게 설정 가능한거여서요

2024-09-18 23:25 UTC, squidjiny commented on good2travel/src/main/java/com/spot/good2travel/service/ItemService.java
> +    public Long createItem(ItemRequest.ItemCreateRequest itemCreateRequest) {
저희 커스텀 계획도 지역구 넣기로 했었어서 추가하셔야 될 것 같습니다 (대신 필수가 아님)

2024-09-18 23:25 UTC, squidjiny commented on good2travel/src/main/java/com/spot/good2travel/controller/ItemController.java
> +                    "<br> 계획의 경우 -> type=PLAN, title, address 필요" +
address도...

2024-09-19 03:34 UTC, X1n9fU commented on good2travel/src/main/java/com/spot/good2travel/domain/Item.java
넹 일단 여기서는 emoji를 item-folder로 옮기고 이에 대한 로직 수정은 #23 에서 진행하겠습니당!

2024-09-19 04:15 UTC, X1n9fU commented on good2travel/src/main/java/com/spot/good2travel/dto/ItemResponse.java
> +//        private Integer temperature; todo 날씨 로직 추가 이후
확인요 !!

2024-09-19 09:08 UTC, squidjiny reviewed
실행이 안되는데요...

2024-09-21 20:29 UTC, squidjiny approved these changes

2024-09-22 04:56 UTC, X1n9fU commented on good2travel/src/main/java/com/spot/good2travel/service/FolderService.java
> +    }
공식적인 것은 폴더에서만 삭제하고, 
공식적이지 않은 것은 item도 같이 삭제해도 괜찮지 않을까 생각이 듭니당.

2024-09-22 04:56 UTC, X1n9fU commented on good2travel/src/main/java/com/spot/good2travel/service/FolderService.java
> +    }
그러면 item에서 delete 로직은 사용하지 않나요?

2024-09-22 04:56 UTC, X1n9fU commented on good2travel/src/main/java/com/spot/good2travel/dto/ItemRequest.java
> +        private String emoji;
그러면 여기도 마찬가지일듯 싶습니닷!

2024-09-22 04:56 UTC, X1n9fU commented on good2travel/src/main/java/com/spot/good2travel/dto/ItemRequest.java
> +        private String emoji;
itemFolderCreateRequest에서 emoji를 업데이트 할 예정이라면 여기에서 image 관련은 삭제해도 괜찮을 것 같습니다.

2024-09-22 04:56 UTC, X1n9fU commented on good2travel/src/main/java/com/spot/good2travel/repository/PostRepository.java
> +            ")")
ㄷㄷ 쩌네요. 직접 쿼리 짜신건가요

2024-09-22 04:56 UTC, X1n9fU commented on good2travel/src/main/java/com/spot/good2travel/dto/FolderResponse.java
> +                    .finishDate(isFinished ? itemFolder.getFinishDate() : null)
false가 아닌 null로 하신 이유가 잇는짓..??

2024-09-22 04:58 UTC, X1n9fU commented on good2travel/src/main/java/com/spot/good2travel/dto/FolderResponse.java
> +        @Schema(example = "\uD83E\uDEE1")
response가 이모지 형태가 아니라 이런 식으로 나오나요?

2024-09-22 05:04 UTC, X1n9fU commented on good2travel/src/main/java/com/spot/good2travel/dto/ItemRequest.java
> +        @Schema(example = "🐋")
22

2024-09-22 05:04 UTC, X1n9fU commented on good2travel/src/main/java/com/spot/good2travel/dto/ItemRequest.java
> +        @Schema(example = "🐋")
emoji는 `itemFolderCreateRequest`에 포함시켰으니 여기는 지울까영?

2024-09-22 05:19 UTC, X1n9fU commented on good2travel/src/main/java/com/spot/good2travel/dto/ItemRequest.java
> +        private String emoji;
`itemFolderCreateRequest`에 포함시켰으니 여기는 지울까요?

2024-09-22 05:19 UTC, X1n9fU commented on good2travel/src/main/java/com/spot/good2travel/dto/ItemRequest.java
> +
생각해보니 `folderService`에서는 커스텀 계획의 emoji를 변경하는 로직은 없었던 거 같아서, item에서 해결하거나 folder에 로직을 추가해야 할 것 같다는 생각이 드네여!!

2024-09-22 05:19 UTC, X1n9fU commented on good2travel/src/main/java/com/spot/good2travel/service/PostService.java
> +    }
[handleIllegalArgumentException] Name for argument of type [java.util.List] not specified, and parameter name information not available via reflection. Ensure that the compiler uses the '-parameters' flag.

Swagger에서 기본값으로 바로 execute 눌렀는데 이런 오류가 떠요 😢

2024-09-22 09:55 UTC, squidjiny commented on good2travel/src/main/java/com/spot/good2travel/service/PostService.java
> +    }
![image](https://github.com/user-attachments/assets/88e7a653-d93e-405e-a823-c398014cc9e4)
잘 되는데 환경 상 문제가 있으신거 같습니다. 데이터베이스 드랍하고 다시 설정해보시는거 추천드립니다.

2024-09-22 09:56 UTC, squidjiny commented on good2travel/src/main/java/com/spot/good2travel/repository/PostRepository.java
> +            ")")
일단 되도록만 짜놔서 추후에 리펙이 필요할거같긴 하네요

2024-09-22 10:03 UTC, squidjiny commented on good2travel/src/main/java/com/spot/good2travel/service/FolderService.java
> +    }
일단 프론트에 먼저 하라고 던져주는게 더 중요할거같아서 삭제 말고 CRU까지 빠르게 구현했습니다.

2024-09-22 14:34 UTC, squidjiny commented on good2travel/src/main/java/com/spot/good2travel/dto/ItemRequest.java
> +        private String emoji;
수정했습니다

2024-09-22 14:34 UTC, squidjiny commented on good2travel/src/main/java/com/spot/good2travel/dto/ItemRequest.java
> +
추가했습니다

2024-09-22 15:20 UTC, merged